- docs/guide/graphql/controllers.md
- docs/guide/graphql/getting-started.md
- examples/graphql/src/api/author/author.controller.ts
- examples/graphql/src/api/book/book.controller.ts
- examples/graphql/src/api/book/book.schema.ts
- packages/graphql/src/decorators/index.ts
- packages/graphql/src/gqlTypes.ts
- packages/graphql/src/index.ts
- packages/graphql/test/unit/createControllerSchemas.test.ts
- packages/graphql/test/unit/generateSchema.test.ts
- packages/reflector/src/shared-types.ts
BREAKING CHANGE: changed graphql arg decorator arguments to be consistent with others
> fix(UnionType): graphql union type

- packages/graphql/src/decorators/index.ts
- packages/graphql/src/types.ts
Allow to explicitly specify a type for a graphql argument
> feat(graphqlArg): allow specify explicit type

- packages/graphql/package-lock.json
- packages/graphql/package.json
- packages/graphql/src/createGraphQLServer.ts
- useful for asynchronous context factory functions
> feat(asyncGraphqlHTTP): now graphqlHTTP can return a promise

- examples/graphql/package-lock.json
- examples/rest/package-lock.json
- examples/rest/package.json
- packages/core/README.md
- packages/core/package-lock.json
- packages/core/package.json
- packages/graphql/package-lock.json
- packages/mongoose/package-lock.json
- packages/mongoose/package.json
- packages/reflector/package-lock.json
moved some dependencies to be optionalDependencies:
in `@davinci/core`
- swagger-ui-express
in `@davinci/mongoose`
- @davinci/core
> chore: using optionalDependencies

- packages/mongoose/package.json
- packages/mongoose/src/createMongooseController.ts
this will allow the host package to ignore the @davinci/core dependency if not necessary
> chore(createMongooseController): lazy requiring functions from @davinci/core

- examples/.eslintrc
- examples/graphql/package-lock.json
- examples/graphql/package.json
- examples/rest/package-lock.json
- examples/rest/package.json
- package-lock.json
- package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/route/decorators/openapi.ts
- packages/core/src/route/openapi/createSchemaDefinition.ts
- packages/core/src/route/types.ts
- packages/core/test/unit/route/decorators/openapi.test.ts
- packages/core/test/unit/route/openapi/createSchemaDefinition.test.ts
- packages/graphql/package-lock.json
- packages/graphql/package.json
- packages/mongoose/package-lock.json
- packages/mongoose/package.json
- packages/mongoose/src/createMongooseController.ts
- packages/mongoose/src/decorators/types.ts
- packages/mongoose/src/hooks.ts
- feat: upgrade to latest mongoose
- feat: use ajv instead of openapi-types
> feat: more upgrades

- .circleci/config.yml
- docs/deploy.sh
- package-lock.json
- package.json
restored missing @vuepress/plugin-google-analytics dependency
> fix: vuepress GA plugin

- .circleci/config.yml
First attempt at getting codecov running on the repo/CircleCI
> chore: upload coverage report to codecov

- packages/core/src/route/createRouter.ts
- packages/core/test/unit/route/createRouter.test.ts
Delay ajv instantiation to a later stage to allow caching instance creation
> feat: delay ajv instantiation

- packages/core/src/route/createRouter.ts
Fixing an issue:
- Missing parameter in return type that broke custom ajv instantiation.
> Fix: schema parameters

- package-lock.json
- package.json
- packages/core/src/lib/interceptors.ts
- packages/core/test/support/chai.ts
- packages/core/test/unit/lib/interceptors.test.ts
The goal of this PR is to provide the primitives for a future agnostic interceptors/middlewares system.
We are moving away from framework-specific middleware implementations, like Express or Fastify middleware.
An interceptor has full control of the next interceptor in the stack, leading to some powerful capabilities:
- execute extra logic before or after method execution
- manipulate the result returned from a method
- manipulate the exception thrown from a method
- override a method depending on specific conditions (e.g., for caching purposes)
> feat(interceptor): added the interceptor primitives

- examples/next-api-express/src/api/customer/customer.controller.ts
- examples/next-api-express/src/index.ts
- packages/core/package.json
- packages/core/src/context/context.ts
- packages/core/src/context/index.ts
- packages/core/src/interceptor/decorator.ts
- packages/core/src/interceptor/interceptor.ts
- packages/core/src/interceptor/types.ts
- packages/core/test/unit/context/context.ts
- packages/core/test/unit/interceptor/interceptor.test.ts
- packages/http-server-express/package.json
- packages/http-server/package-lock.json
- packages/http-server/package.json
- packages/http-server/src/HttpServerModule.ts
- packages/http-server/test/unit/HttpServerModule.test.ts
- packages/reflector/package.json
This PR provides support for injecting the context both as a method parameter and as an interceptor parameter.
A new `setContextFactory` method on the HttpServerModule class allows specifying the context factory function.
> feat: context support

- packages/http-server-express/src/ExpressHttpServer.ts
- packages/http-server-express/test/unit/ExpressHttpServer.test.ts
- packages/http-server-fastify/src/FastifyHttpServer.ts
- packages/http-server-fastify/test/unit/FastifyHttpServer.test.ts
- packages/http-server/src/AjvValidator.ts
- packages/http-server/src/HttpServerModule.ts
- packages/http-server/src/decorators/route.ts
- packages/http-server/src/types.ts
- packages/http-server/test/unit/HttpServerModule.test.ts
- packages/http-server/test/unit/decorators.test.ts
Allow DaVinci methods to inject native req/res objects, to access Express or Fastify specific functionalities.
> [next] feat(httpServer): decorators for accessing native req and res

- packages/http-server/src/AjvValidator.ts
- packages/http-server/src/decorators/types.ts
- packages/http-server/test/unit/AjvValidator.test.ts
Added ability to disable the validation for a specific parameter of a route
> [next] feat(httpServer): option to disable validation

- examples/next-api-express/package-lock.json
- examples/next-api-express/package.json
- examples/next-api-fastify/package-lock.json
- examples/next-api-fastify/package.json
- packages/core/src/di.ts
- packages/core/src/entity/EntityRegistry.ts
- packages/core/src/index.ts
- packages/http-server-express/test/unit/ExpressHttpServer.test.ts
- packages/http-server-fastify/test/unit/FastifyHttpServer.test.ts
- packages/http-server/src/AjvValidator.ts
- packages/http-server/src/HttpServerModule.ts
- packages/http-server/src/index.ts
- packages/http-server/src/types.ts
- packages/http-server/test/unit/AjvValidator.test.ts
- packages/http-server/test/unit/HttpServerModule.test.ts
- website/docs/modules/http-server/express.md
- website/docs/modules/http-server/fastify.md
This PR aims to make the validation logic more flexible, making it easy to substitute Ajv with other Javascript validation libraries or custom ones.
At the same time, it allows customizing the Ajv initialization, for fine-tuned validation behaviours.
FastifyHttpServer and ExpressHttpServer now accept an additional parameter `validationFactory`, a function that take a route definition as a parameter and must return a validation function.
E.g.
```ts
new FastifyHttpServer({
validationFactory(route) {
// use following route info as needed
const { path, verb, parametersConfig } = route;
// [...]
return data => {
// perform validation logic
};
}
});
```
Implemented a new `createAjvValidator` function that allow an easy and flexible configuration of the validation logic, via Ajv
Example 1, pass …
> refactor: next validation

- examples/next-api-mongoose/src/index.ts
- packages/health-checks/src/HealthChecksModule.ts
- packages/http-server-express/src/ExpressHttpServer.ts
- packages/http-server-express/test/unit/ExpressHttpServer.test.ts
- packages/http-server-fastify/src/FastifyHttpServer.ts
- packages/http-server-fastify/test/unit/FastifyHttpServer.test.ts
- packages/http-server/src/HttpServerModule.ts
- packages/http-server/src/types.ts
- packages/http-server/test/unit/HttpServerModule.test.ts
- packages/messaging-amqp/src/AmqpModule.ts
- packages/mongoose/src/MongooseModule.ts
- packages/mongoose/test/unit/MongooseModule.test.ts
- packages/openapi/src/OpenAPIModule.ts
Other changes:
- simplified HttpServer generics
> [next] feat(httpServer): added ability to register global interceptors

- packages/http-server/src/decorators/types.ts
- packages/openapi/src/OpenAPIModule.ts
- packages/openapi/src/index.ts
- packages/openapi/src/types.ts
- packages/openapi/test/unit/OpenAPIModule.test.ts
Other changes:
- moved openapi-related properties out from the http-server package
> feat(openapi): added ability to specify default responses

- examples/next-api-express/src/api/customer/customer.controller.ts
- examples/next-api-express/src/interceptors/logInterceptor.ts
- examples/next-api-fastify/src/api/customer/customer.controller.ts
- examples/next-api-fastify/src/interceptors/logInterceptor.ts
- packages/http-server/src/HttpServerModule.ts
- packages/http-server/src/types.ts
- packages/http-server/test/unit/HttpServerModule.test.ts
This PR tries to simplify the process of passing the generic types to the HttpServerInterceptor interface
> chore: next httpinterceptor types

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
The hope is to solve some high severity alerts on dependabot
> feat(docs): updated dependencies

- packages/mongoose/package-lock.json
- packages/mongoose/package.json
- packages/mongoose/src/hooks.ts
Allow mongoose 8 as a peer dependency in davinci/mongoose.
> feat: allow mongoose 8
