HPInc/davinci

examples/graphql/package-lock.json, examples/graphql/package.json, examples/rest/package-lock.json, examples/rest/package.json
This PR removes some testing/linting libraries (`mocha`, `should`, `tslint` and `@types/mocha`) from the example projects since they weren't actually in use and one of mocha's dependencies had a security vulnerability.
=> fix: remove unused testing npms

packages/core/src/route/openapi/createPaths.ts, packages/core/src/route/types.ts, packages/core/test/unit/route/decorators/route.test.ts, packages/core/test/unit/route/openapi/createPaths.test.ts
Related to: https://github.com/Oneflow/workforce-api/pull/446#issue-442644353
```ts
@route.controller({ basepath: '/' })
class MyClass {
@route.post({ path: '/', summary: 'Create', description: 'Create a Planet or a Star' })
// we can now pass an enum type. In this case, the body could either be a Planet or a Star
post(@route.body({ enum: [Planet, Star] }) items: Planet | Star) {
return items;
}
}
```
=> feat: added the ability to specify enum parameter types

examples/rest/src/index.ts, packages/core/src/route/createRouter.ts, packages/core/test/unit/route/createRouter.test.ts
So that the routes get attached directly into it.
Needed for displaying correctly the name of the routes in newrelic APM.
=> feat: allow passing the express instance as parameter

packages/core/src/express/middlewares/errorHandler.ts
This `console.error` was causing a huge stack trace to be dumped in the middle of some mocha unit tests I was running which caused me to spend time investigating why it was happening.
We already use `debug` to log the error object further up the function, it doesn't seem useful to also console.error the object again later on. Having said that, we could potentially move the debug call further down to give us a better idea of the error we actually return to the client?
=> fix: don't use console

examples/graphql/package-lock.json, examples/graphql/package.json, examples/rest/package-lock.json, examples/rest/package.json, packages/core/package-lock.json, packages/core/package.json, packages/graphql/package-lock.json, packages/graphql/package.json, packages/mongoose/package-lock.json, packages/mongoose/package.json
This PR updates lodash in all packages (as opposed to Dependabot's PRs which is one-per-package). 
The update fixes the following alerts:
https://github.com/HPInc/davinci/network/alerts
=> fix: update lodash due to security vulnerability

packages/core/package-lock.json, packages/core/package.json
As the title says - there's no need for `@types/mocha` to be a standard dependency, it's only useful for development/build.
=> fix: moved @types/mocha to devDependencies

docs/guide/basics/swagger-ui.md
According to both Swagger/OpenAPI 2.0: 
https://swagger.io/specification/v2/#infoObject
and OpenAPI 3.0:
https://swagger.io/specification/#info-object
the `info` definition **requires** `title`, and `name` isn't a recognized property. 
This PR fixes the docs to describe that correctly.
=> fix: rename swagger 'name' field to 'title'

packages/graphql/src/queryHelpers.ts, packages/graphql/test/unit/queryHelpers.tests.ts
fixed issue with multiple operators on the same property. Example
```
// grapqhl query to transform in mongodb query
{
myNumber: { GT:1, LT: 10 }
}
// transformation with previous behaviour
{
myNumber: { $lt: 10 }
}
// transformation with fixed behaviour
{
myNumber: { $gt:1, $lt: 10 }
}
```
=> fix(graphql): fixed an issue with multiple operators

packages/core/src/errors/httpErrors.ts
`[any]` means a single element array while `any[]` means an array with any elements
=> fix: change errors type

packages/core/package-lock.json, packages/core/package.json, packages/core/src/route/decorators/openapi.ts, packages/core/src/route/types.ts, packages/core/test/unit/route/openapi/createSchemaDefinition.test.ts
This will allow creating complicated validation rules using [dependencies](https://json-schema.org/understanding-json-schema/reference/object.html#dependencies).
=> feat: allow additional fields in openapi definition

docs/deploy.sh
The `gh-pages` branch has nothing to build/etc as it is only used for GitHub Pages content.
This PR simply adds `[skip ci]` to the commit made as part of the commit to that branch, which informs CircleCI that it doesn't need to do anything.
=> fix: skip CI when committing to docs branch

.circleci/config.yml, packages/mongoose/package.json
Switches from the legacy `@oneflow` scope to the correct `@davinci` scope when generating the `.npmrc` file in the CircleCI pipeline.
=> fix: switch to correct npm scope

lerna.json
During the CI/CD process, Lerna actually commits and pushes changes to the Git repo, bumping the version numbers in the package.json files and including the latest changes in the changelog file. 
These changes don't need to trigger a new build, so this PR adds `[skip ci]` to Lerna's "publish" commit message.
=> fix: skip ci during publish commit

examples/rest/src/api/customer/customer.schema.ts, packages/core/src/route/openapi/createSchemaDefinition.ts, packages/core/src/route/types.ts, packages/core/test/unit/route/decorators/openapi.test.ts, packages/core/test/unit/route/openapi/createSchemaDefinition.test.ts, packages/mongoose/src/createMongooseController.ts
Previously the openapi options they had to be passed inside  a 'rawSchemaOptions' property.
With the changes contained in the PR the openapi options can be passed a the root level
=> chore(openapi): 'prop' and 'definition' decorators now support root-level evel openapi props

.circleci/config.yml
Upgraded CircleCI configs to run **checkout_and_test** job to for both mongo 3.6 and mongo 4.4 versions. Use cached build from `mongo4_4` executor in `publish` and `publish_docs` jobs.
https://circleci.com/blog/circleci-matrix-jobs/
=> feat: circleci matrix job

packages/core/package-lock.json, packages/core/package.json, packages/core/src/route/createRouter.ts
> all formats are separated to ajv-formats package - they have to be explicitly added if you use them.
> -- https://github.com/ajv-validator/ajv/releases/tag/v7.0.0
=> fix: install and use ajv-formats

examples/rest/src/api/customer/customer.schema.ts, packages/core/src/route/openapi/createSchemaDefinition.ts, packages/mongoose/src/decorators/index.ts, packages/mongoose/src/generateModel.ts, packages/mongoose/test/unit/decorators/index.test.ts, packages/mongoose/test/unit/generateModel.test.ts
- feat: added mgoose.schema() decorator
- fix: do not pass top level schema options down to sub-schemas
=> feat(mongoose): better handling of schema options

docs/guide/database/mongoose.md
Updated documentation for mongoose hooks.
**Validate** middleware for afterWrite/beforeWrite hooks is not supported [(the list of supported middlewares)](https://github.com/HPInc/davinci/blob/master/packages/mongoose/src/hooks.ts#L19)
=> docs: update mongoose hooks documentation

packages/core/src/route/createRouter.ts, packages/core/src/route/decorators/openapi.ts, packages/core/src/route/index.ts, packages/core/src/route/openapi/Resource.ts, packages/core/src/route/openapi/createOpenapiSchemaDefinitions.ts, packages/core/src/route/openapi/createPaths.ts, packages/core/src/route/openapi/openapiDocs.ts, packages/core/test/unit/route/openapi/createOpenapiSchemaDefinitions.test.ts, packages/core/test/unit/route/openapi/openapiDocs.test.ts
There are situations where it may be preferable to manually create OpenAPI definitions and add them to the OpenAPI Document.
```ts
@openapi.definition()
export class PaginationQuery {
@openapi.prop({ 
type: null, 
oneOf: [{ $ref: '#/definitions/PopulateQuery' }, { type: 'string' }] 
})
$populate?: PopulateQuery | string;
}
```
In this example, we want to be able to define the type of the **$populate** property to be either `PopulateQuery` or `string`.
But the class reflection and traversal won't be executed because `type` is set to `null` to allow the advanced use of `oneOf`, so the `PopulateQuery` definition is not tracked and won't be added in the OpenAPI document.
The changes in this PR allow to manually add a definition to the OpenAPI main document:
```ts
import { openapiDocs, …
```
=> feat(openapi): expose function to generate openapi definitions

packages/core/src/express/boot/index.ts
This PR fixes a leftover `debug` namespace from the original `of-base-api` library.
No API functionality has changed with this PR, just the namespace used when outputting logs.
=> fix: use correct 'debug' namespace

packages/core/src/route/createRouter.ts
* Fix: pass through ajv instance when performing json parsing.
=> Fix: pass ajv instance on json parsing

examples/rest-custom-ajv/src/index.ts, packages/core/src/route/createRouter.ts
* Pass current parameter to ajv factory method so that client is able to choose whether or not to enable some features.
* Updated examples.
=> Fix: Pass current parameter to ajv factory

.eslintrc, examples/graphql/package-lock.json, examples/graphql/package.json, examples/rest-custom-ajv/package-lock.json, examples/rest-custom-ajv/package.json, examples/rest/package-lock.json, examples/rest/package.json, package-lock.json, package.json, packages/core/package-lock.json, packages/core/package.json, packages/core/src/createApp.ts, packages/core/src/route/createRouter.ts, packages/core/src/route/types.ts, packages/core/test/mocha.opts, packages/graphql/package-lock.json, packages/graphql/package.json, packages/graphql/src/createControllerSchemas.ts, packages/graphql/src/createGraphQLServer.ts, packages/graphql/src/generateSchema.ts, packages/graphql/src/types.ts, packages/graphql/test/mocha.opts, packages/mongoose/package-lock.json, packages/mongoose/package.json, packages/mongoose/test/mocha.opts, packages/reflector/package-lock.json, packages/reflector/package.json, packages/reflector/src/shared-types.ts, packages/reflector/test/mocha.opts
This PR updates the following TypeScript dependencies to the latest versions
- `typescript` from `3.7.5` to `4.3.5`
- `tslib` from `1.9.3` to `2.3.0`
- `ts-node` from `8.3.0` to `10.0.0`
- `@typescript-eslint/eslint-plugin` from `2.7.0` to `4.28.1`
- `@typescript-eslint/parser` from `2.7.0` to `4.28.1`
- `bluebird` from multiple versions to `3.7.2`
It makes as few code changes as possible, the majority consisting of moving a few types within the file to eliminate "used before defined" errors. 
This PR explicitly disables some `ban-types` rules which were introduced at some point in a more recent release.
Da Vinci currently uses all three (`Function`, `object` and `{}`) so to avoid refactoring a lot of code in this PR, I disabled the rule and will create a subsequent PR that makes the …
=> Update to newest TypeScript dependencies

packages/graphql/package-lock.json, packages/graphql/package.json, packages/graphql/src/createGraphQLServer.ts, packages/graphql/src/decorators/index.ts, packages/graphql/test/unit/createGraphQLServer.test.ts
- the fieldResolver returnType parameter is now of type `ReturnTypeFuncValue`. It allows to return Union types. ([link](https://github.com/HPInc/davinci/compare/fix/graphql-resolver-union?expand=1#diff-c66b7b9b380c52d7e590a51ffea6d20d674fce3459e835f92340654c30f0b18bR124))
- fixed a variable access issue that was preventing DaVinci to start on nodejs14+ ([link](https://github.com/HPInc/davinci/compare/fix/graphql-resolver-union?expand=1#diff-f311c62bb2cd250d058384421cf4a8bfc86240c83e1fb1e2c0cf5d70d4ca56e4R54))
- added createGraphQLServer unit test
=> fix: graphql resolver union + failure on node14

.circleci/config.yml, codecov.yml
This PR configures [Codecov flags](https://docs.codecov.com/docs/flags) on the repository. 
This gives us better visibility on the coverage for each package in the Lerna workspace, as shown below in the Codecov comment:
=> chore: codecov flags for lerna packages

packages/core/src/express/decorators/context.ts, packages/core/src/express/decorators/express.ts, packages/core/src/route/decorators/openapi.ts, packages/core/src/route/decorators/route.ts, packages/core/test/unit/express/decorators/context.test.ts, packages/core/test/unit/express/decorators/express.test.ts, packages/core/test/unit/route/createRouter.test.ts, packages/graphql/src/decorators/index.ts, packages/graphql/src/generateSchema.ts, packages/graphql/src/types.ts, packages/graphql/test/unit/decorators/index.test.ts, packages/mongoose/src/decorators/index.ts
This PR adds the correct TypeScript decorator types, to improve type-safety and understandability of the codebase.
It also slightly refactors the GraphQL `@fieldResolver` decorator to improve the behaviour slightly:
- It no longer has the wrong signature (previously was the `ParameterDecorator` signature)
- It now has an interface that defines the actual metadata that we capture
- It now ensures the fieldResolver doesn't clash with another fieldResolver on the same class+property
I also added a couple of tests for verifying duplicate decorator functionality on the express decorators
=> Improved decorator types

packages/core/src/route/createRouter.ts, packages/core/test/unit/route/createRouter.test.ts
This PR fixes #31. 
As far as I can tell, it's currently an edge case, as all usages of `@route.controller({ ... })` explicitly specify a `basepath` value. The issue above was for cases where `basepath` wasn't defined. 
As such, although it's a breaking change, it should break very little. 
Here's the new test that recreates the use case where a basepath isn't specified:
```TypeScript
it('should have correct routes when no basepath defined on the controller', () => {
const app = express();
@route.controller() // no 'basepath' set, derive from controller name instead ('greet')
class GreetController {
@route.get({ path: '/hello', summary: 'Oh hello!' })
hello() {}
}
createRouter({ Controller: GreetController, router: app });
const swagger = generateFullSwagger({});
const expectedPath = …
```
=> Fix express route path when controller `basepath` isn't explicitly defined

packages/core/src/route/createRouter.ts, packages/core/src/route/openapi/openapiDocs.ts, packages/core/test/unit/route/createRouter.test.ts, packages/core/test/unit/route/openapi/openapiDocs.test.ts
This is an update to the previous `basepath` PR #84. 
After discussing with @pierissimo, it was decided that defaulting `basepath` to `resourceName` when it wasn't defined was not the preferable solution. Instead, we now default the `basepath` to `/` if it wasn't defined.
This PR makes that change while also ensuring the Swagger Docs generation is fixed to be consistent (which is what issue #31 originally reported). 
It also adds even more unit tests, so we can be extra sure that it is now behaving as expected :)
=> fix: default basepath to / instead of resource name

.circleci/config.yml
This PR adds MongoDB 5.0 to the CircleCI test matrix and removes MongoDB 4.2 (but leaves 4.4).
=> chore: test against MongoDB 5.0 in CI/CD

packages/core/package-lock.json, packages/core/package.json, packages/core/src/route/createRouter.ts, packages/core/src/route/openapi/openapiDocs.ts, packages/mongoose/package-lock.json
Use path.join to concatenatepath creates wrong api paths when davinci is used in windows OS.
So that: 
-  url.resolve() is the same as path.join() but it's deprecated <https://nodejs.org/api/url.html#url_url_resolve_from_to>
-  Davinci uses url-join library to join path
=> Fix: Build path with path.join is error prone depending OS

packages/core/src/createApp.ts, packages/core/test/unit/createApp.test.ts
This PR add a new attribute `port` to DaVinciOptions. The reason for this is to be able to define a port to listen over the options given to the createApp method.
I'm suggesting/doing this change because not always env vars are free to be used. To give you more context, 3D team is trying to create an API that will run alongside a Bucket Closer service, but we had a issue, the existing service already use the `PORT` env var and DaVinci is trying to use the same port, so defining the port trough options parameter would solve this and make DaVinci more flexible.
=> feat: adding port configuration on davinci options

package-lock.json
Bump following vulnerable packages:
* acorn, lodash, elliptic, ssri and y18n
All of them are minor versions. Reviewed changelog and no breaking changes.
Pending a few high ones that can't be addressed without replacing vuepress. I will raise an exception for them.
=> Fix: npm security updates

packages/mongoose/src/decorators/index.ts, packages/mongoose/test/unit/decorators/index.test.ts
Changes from https://github.com/HPInc/davinci/pull/83 cause build issues when using virtual to decorate a property. 
Adding return type as PropertyDecorator to fix it. Tested locally and added a test to cover this behavior.
=> Fix: Allow virtual decorator on properties

package-lock.json
Bump url-parse, follow-redirects & node-fetch
=> Chore: upgrade vulnerable dependencies

docs/guide/README.md, docs/guide/basics/context.md, docs/guide/basics/swagger-ui.md, examples/rest/src/index.ts, package-lock.json, packages/core/src/route/createRouter.ts, packages/core/test/support/createAppInstance.ts, packages/core/test/unit/route/createRouter.test.ts
As pointed out by vlad, we are still using a deprecated createRouter method in examples. Updated to use the latest one.
Added also some documentation to createRouter function and parameters.
=> Fix: documentation

packages/core/src/route/createRouter.ts, packages/core/src/route/decorators/route.ts, packages/core/src/route/openapi/createPaths.ts, packages/core/test/unit/route/decorators/route.test.ts, packages/mongoose/src/createMongooseController.ts
It's meant to avoid registering multiple definitions with the same name.
This is particularly important after the AJV cache mechanism introduced recently
The type for the QueryParameters['$populate'] has been modified to allow passing an array of population objects
=> fix: createMongooseController now produces definitions with prefixed names

.prettierrc, examples/next/package-lock.json, examples/next/package.json, package.json, packages/reflector/.eslintrc, packages/reflector/README.md, packages/reflector/package-lock.json, packages/reflector/package.json, packages/reflector/src/index.ts, packages/reflector/src/reflect.ts, packages/reflector/src/shared-types.ts, packages/reflector/test/mocha.opts, packages/reflector/test/unit/reflect.test.ts, packages/reflector/tsconfig.json, packages/reflector/tsconfig.release.json
This PR contains a brand new version of the Reflector package.
The reflector package is used for the Typescript reflection, it allows the introspection of Typescript classes and functions by returning an object graph containing classes, methods, parameters and also decorator's metadata.
Instead of writing a Reflection library from scratch, we are now relying on the [@plumier/reflect](https://github.com/plumier/plumier/tree/master/packages/reflect), effectively proxying functions and types from the library.
=> feat(reflector): using @plumier/reflector

packages/core/src/App.ts, packages/core/src/Module.ts, packages/core/test/unit/App.test.ts, packages/health-checks/test/unit/HealthChecksModule.test.ts, packages/http-server-express/src/ExpressHttpServer.ts, packages/http-server-fastify/src/FastifyHttpServer.ts, packages/http-server/test/unit/HttpServerModule.test.ts
A new App lifecycle stage has been added, that allows modules to perform actions after registering them.
The new lifecycle schema for the App is:
`'unloaded' ->'registering' ->'registered' ->'initializing' ->'initialized' ->'destroying' ->'destroyed'`
Additionally, a new `onRegister` hook has been made available for modules.
That differentiation between the registration and initialization phase is particularly important for the Fastify and Express modules:
The routes registration happens in the App registration phase, while the actual HTTP server start will happen in the initialization phase.
This allows other modules (OpenAPI or HealthCheck for example) to register routes on the HttpModule, before starting the server.
=> [next] feat(lifecycle): added onRegister lifecycle hook for modules

examples/next-api-express/src/index.ts, examples/next-api-fastify/src/index.ts, packages/core/src/App.ts, packages/core/src/Module.ts, packages/core/test/unit/App.test.ts, packages/core/test/unit/Module.test.ts, packages/http-server/test/unit/HttpServerModule.test.ts
- core: added a new `onRegister` lifecycle hook
- core: Now modules have an internal status field
- core: added ability to respond to shutdown signals
=> refactor: onRegister phase + modules internal status field

packages/mongoose/src/generateModel.ts, packages/mongoose/src/hooks.ts, packages/mongoose/src/index.ts, packages/mongoose/test/unit/generateModel.test.ts, packages/mongoose/test/unit/hooks.test.ts
- renamed davinciCtx to davinciContext (latest from master branch)
- generateSchema now instantiates a new Mongoose Schema by default
- added typing for passing davinciContext within the mongoose query options
=> fix(mongoose): renamed to davinciContext, changed generateSchema behaviour

examples/next-amqp/src/subscribers/customer/customer.subscriber.ts, packages/core/src/App.ts, packages/core/test/unit/App.test.ts, packages/health-checks/src/HealthChecksModule.ts, packages/http-server/src/HttpServerModule.ts, packages/messaging-amqp/src/AmqpModule.ts, packages/messaging-amqp/src/ChannelManager.ts, packages/messaging-amqp/src/index.ts, packages/messaging-amqp/test/integration/AmqpModule.test.ts
Added the ability to inject the ChannelManager within the Controllers and other classes where needed, so that publishing messages is trivial.
- Instantiating controllers in App
- removed reflection cache in App as already provided by @plumier/reflect
=> feat(Amqp): provide ability to inject ChannelManager in controllers

packages/core/src/lib/object-utils.ts, packages/core/test/unit/lib/object-utils.tests.ts, packages/mongoose/src/generateModel.ts, packages/mongoose/test/unit/generateModel.test.ts
The changes included in the PR solve an issue when creating schemas having properties with field name 'type'.
That clashes with the internal `type` used to define the SchemaType.
To avoid the clashing, the typeKey value has been set to `$type`
=> fix(mongoose): set typeKey schema option to '$type'

packages/core/src/entity/jsonSchemaTypes.ts, packages/mongoose/src/decorators/types.ts, packages/mongoose/src/generateModel.ts, packages/mongoose/test/unit/generateModel.test.ts
This PR reverts a previous change that explicitly set the mongose typeKey to be `$type`, that was introduced in order to support properties name `type`.
Unfortunately, the change breaks the support for keywords on sub-schemas.
Better @mgoose.prop() and @entity.prop() code suggestion
=> fit: revert mongoose typekey

packages/http-server/src/HttpServerModule.ts, packages/http-server/src/types.ts, packages/http-server/test/unit/HttpServerModule.test.ts
This PR add a new `querystringJsonParsing` parameter that can enable the parsing of jsonified querystring parameters:
e.g.
```
GET /api/customers?query={"where":{"firstname": "John"}}
```
=> feat: added parameter that enables jsonified querystring parsing

packages/http-server-fastify/README.md
A tiny error probably due to copy+paste
=> chore: fix typo in readme

packages/openapi/package.json
The version mismatch was causing some conflicts.
The http-server dependency was removed altogether
=> fix(openapi) removed http server from peerDependency

packages/core/src/entity/EntityDefinition.ts, packages/core/test/unit/entity/EntityDefinition.tests.ts
There are cases where is desirable for the type not to be passed to the resulting JSON schema.
for example when using compound keywords (anyOf, allOf, oneOf)
Example:
```ts
@entity()
class Customer {
@entity.prop({
type: false,
anyOf: [
{
type: 'number'
},
{
type: 'string'
}
]
})
address: number | string;
}
```
=> feat(entity): ability to disable type detection by passing false or null

packages/core/src/entity/EntityDefinition.ts, packages/core/test/unit/entity/EntityRegistry.tests.ts, packages/http-server/src/AjvValidator.ts, packages/http-server/test/unit/AjvValidator.test.ts, packages/openapi/src/OpenAPIModule.ts, packages/openapi/test/unit/OpenAPIModule.test.ts
This PR allows you to use a schema that references itself within an entity. 
```ts
// example 1
@entity()
class Populate {
@entity.prop()
populate: Populate;
}
// example 2 -> array
@entity()
class Populate {
@entity.prop({ type: [Populate] })
populate: Array<Populate>
}
// example 3 -> nested inside anyOf, allOf, oneOf keywords
@entity()
class Populate {
@entity.prop({ anyOf: [{ type: 'string' }, Populate] })
populate: string | Populate;
}
```
=> feat(entity): added support for recursive schemas

.circleci/config.yml, packages/reflector/package-lock.json, packages/reflector/package.json
`@plumier/reflect` in the `reflector` package as been upgraded to v1.1.3
The latest version of `@plumier/reflect` supports configuring the `target` and `lib` properties of the tsconfig.json with modern ES* values, compatible with Node.js v18, as suggested [here](https://github.com/tsconfig/bases/blob/main/bases/node18.json)
=> feat(reflector): updated to @plumier/reflect@1.1.3

.circleci/config.yml
* Due to circleci cache, tags are not refreshed if in the cache, trying to solve fetching tags before publish step.
=> Fix: fetch git tags before publish to avoid cache issues

packages/http-server/src/HttpServerModule.ts, packages/openapi/.mocharc.js, packages/openapi/src/OpenAPIModule.ts, packages/openapi/test/unit/OpenAPIModule.test.ts, packages/openapi/tsconfig.cjs.release.json, packages/openapi/tsconfig.esm.release.json
This pull request aims to enhance the compatibility of our framework to support edge runtimes such as Cloudflare Workers, Vercel Edge, etc. 
Edge computing is become crucial for applications that require low latency and real-time processing. Thus, making our framework compatible with edge runtimes is a significant improvement.
1. **Conditional loading of native modules:** Native Node.js modules are now conditionally loaded by checking the `globalThis.EdgeRuntime` beforehand. This ensures that native modules are only loaded in the Node.js runtime.
2. **Using native Node.js modules only when necessary:** The use of native Node.js modules has been limited to only when it is absolutely necessary.
=> feat: improve edge compatibility

.circleci/config.yml, packages/mongoose/src/hooks.ts, packages/mongoose/test/unit/hooks.test.ts
- Adding missing parameters in `afterWrite` hook.
- Also added `findByIdAndUpdate` test to check `findOneAndUpdate` hook handler is called on that case.
- REMOVED node 14 support since circleCI was failing!!
=> fix: add missing params in afterWrite hook
